# **DATA ANALYTICS INTERNSHIP**

**Intern:** Narmadha V  
**Organization:** DecodeLabs  
**Batch:** 2026  

## **Project 3 : SQL Data Analysis**

### Step 1 — Import Libraries

In [1]:
import pandas as pd
import sqlite3

### Step 2 — Preview Dataset

In [3]:
df = pd.read_excel("Cleaned_Dataset.xlsx")
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,CalculatedPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,2504.04

### Step 3 — Create SQL Database

In [4]:
conn = sqlite3.connect("project3.db")

### Step 4 — Convert DataFrame to SQL Table

In [5]:
df.to_sql("orders",conn,if_exists="replace",index=False)

1200

### Step 5 — Verify Table

In [6]:
query = """

SELECT * FROM orders
LIMIT 5

"""

pd.read_sql_query(query,conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,CalculatedPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,2504.04

- Displayed sample records to verify table creation.

### Step 6 — Count Total Orders

In [7]:
query = """

SELECT COUNT(*) AS Total_Orders
FROM orders

"""

pd.read_sql_query(query,conn)

   Total_Orders
0          1200

### Step 7 — Count Unique Customers

In [8]:
query = """

SELECT COUNT(DISTINCT CustomerID) AS Customers
FROM orders

"""

pd.read_sql_query(query,conn)

   Customers
0       1189

### Step 8 — Count Products

In [11]:
query = """

SELECT COUNT(DISTINCT Product) AS Products
FROM orders

"""

pd.read_sql_query(query,conn)

   Products
0         7

### Step 9 — Total Revenue

In [12]:
query = """

SELECT SUM(TotalPrice) AS Revenue
FROM orders

"""

pd.read_sql_query(query,conn)

      Revenue
0  1264761.96

### Step 10 — Average Order Value

In [13]:
query = """

SELECT AVG(TotalPrice) AS Average_Customer_Spending
FROM orders

"""

pd.read_sql_query(query,conn)

   Average_Customer_Spending
0                  1053.9683

- Measured average customer spending per order.

### Step 11 — Average Quantity Purchased

In [14]:
query = """

SELECT AVG(Quantity) AS Avg_Quantity
FROM orders

"""

pd.read_sql_query(query,conn)

   Avg_Quantity
0      2.945833

- Calculated average units purchased per transaction i.e., ~ 3

### Step 12 — Revenue by Payment Method

In [15]:
query = """

SELECT PaymentMethod, SUM(TotalPrice) AS Revenue
FROM orders

GROUP BY PaymentMethod
ORDER BY Revenue DESC

"""

pd.read_sql_query(query,conn)

  PaymentMethod    Revenue
0   Credit Card  263847.63
1        Online  262442.94
2          Cash  259786.29
3     Gift Card  246323.92
4    Debit Card  232361.18

- Compared revenue across payment methods.

### Step 13 — Top 10 Revenue Products

In [16]:
query = """

SELECT Product, SUM(TotalPrice) AS Revenue
FROM orders

GROUP BY Product
ORDER BY Revenue DESC
LIMIT 10

"""

pd.read_sql_query(query,conn)

   Product    Revenue
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41
5     Desk  167459.93
6    Phone  151722.39

### Step 14 — Order Status Analysis

In [17]:
query = """

SELECT OrderStatus, COUNT(*) AS Orders
FROM orders

GROUP BY OrderStatus
ORDER BY Orders DESC

"""

pd.read_sql_query(query,conn)

  OrderStatus  Orders
0   Cancelled     250
1    Returned     247
2     Pending     237
3     Shipped     235
4   Delivered     231

- Analyzed distribution of order completion status.

### Step 15 — Revenue by Referral Source

In [18]:
query = """

SELECT ReferralSource, SUM(TotalPrice) AS Revenue
FROM orders

GROUP BY ReferralSource
ORDER BY Revenue DESC

"""

pd.read_sql_query(query,conn)

  ReferralSource    Revenue
0      Instagram  275285.45
1          Email  261808.55
2         Google  250441.48
3       Facebook  250410.90
4       Referral  226815.58

 - Measured revenue contribution from referral channels.

### Step 16 — Highest Value Orders

In [19]:
query = """

SELECT OrderID, CustomerID, Product, Quantity, UnitPrice, TotalPrice, PaymentMethod
FROM orders

ORDER BY TotalPrice DESC
LIMIT 10

"""

pd.read_sql_query(query,conn)

,OrderID,CustomerID,Product,Quantity,UnitPrice,TotalPrice,PaymentMethod
0,ORD200789,C57276,Tablet,5,691.28,3456.40,Online
1,ORD201122,C38840,Monitor,5,678.19,3390.95,Online
2,ORD200632,C67260,Laptop,5,678.16,3390.80,Gift Card
3,ORD200469,C13877,Chair,5,676.98,3384.90,Cash
4,ORD200328,C18404,Tablet,5,674.04,3370.20,Online
5,ORD200107,C16775,Printer,5,670.75,3353.75,Gift Card
6,ORD200326,C65986,Laptop,5,670.48,3352.40,Gift Card
7,ORD201065,C47778,Printer,5,666.80,3334.00,Debit Card
8,ORD201031,C59183,Phone,5,664.51,3322.55,Debit Card
9,ORD200463,C25276,Laptop,5,662.78,3313.90,Debit Card

### Step 17 — Products with Revenue Above 10000

In [20]:
query = """

SELECT Product, SUM(TotalPrice) AS Revenue
FROM orders

GROUP BY Product
HAVING Revenue > 10000

"""

pd.read_sql_query(query,conn)

   Product    Revenue
0    Chair  195620.11
1     Desk  167459.93
2   Laptop  192126.56
3  Monitor  175651.41
4    Phone  151722.39
5  Printer  195612.61
6   Tablet  186568.95

- Filtered products exceeding the revenue threshold.

### Step 18 — Customers with Highest Spending

In [21]:
query = """

SELECT CustomerID, SUM(TotalPrice) AS Spending
FROM orders

GROUP BY CustomerID
ORDER BY Spending DESC
LIMIT 10

"""

pd.read_sql_query(query,conn)

  CustomerID  Spending
0     C38840   5723.23
1     C57276   3456.40
2     C67260   3390.80
3     C13877   3384.90
4     C18404   3370.20
5     C16775   3353.75
6     C65986   3352.40
7     C47778   3334.00
8     C59183   3322.55
9     C25276   3313.90

### Step 19 — Close Connection

In [22]:
# Closed SQL connection after analysis.
conn.close()